#! /bin/sh
#
# Use the below command to add a line to the CronTab file
# Remember!  Change the path to the file
#
echo "*/60 * * * * /usr/bin/sudo -H /home/pi/ckinet/ckinet.sh >> /dev/null 2>&1" >> /etc/crontab

